### ISSUE TITLE
Add numpy/networkx enabled version AbstractPlayer

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#324]
People were complaining why there was no pre-setup code using numpy and networkx. We might help them by providing another AbstractPlayer with wrapper support for those.

**Comment by Debilski** [comment]
WDYT?

**Comment by otizonaizit** [comment]
What does "pre-setup" code means? Does it mean "import numpy"? I guess 
no...

**Comment by Debilski** [comment]
Well okay, I thought someone would have an obvious use case. :)

Not sure if just wrapping the maze in a True/False numpy array makes much sense either. But if we have a smart idea, we can silence the voices saying that this project hasn’t got much to do with the science reality if they cannot even use numpy.

Networkx makes more sense (and we could drop our graph.py algorithms – which is mainly the reason I am bringing this up again) but then again it may give them too much of a head start.

So yeah, I am probably not too convinced myself either.

**Comment by otizonaizit** [comment]
>Well okay, I thought someone would have an obvious use case. :)
Well, overengineering and YAGNI :P

>Not sure if just wrapping the maze in a True/False numpy array makes 
>much sense either. But if we have a smart idea, we can silence the 
>voices saying that this project hasn’t got much to do with the science 
>reality if they cannot even use numpy.
It is all to do with science, even if we don't use numpy. They can wrap 
the maze in boolean arrays themselves, if they have a good use case for 
that.

>Networkx makes more sense (and we could drop our graph.py algorithms 
>– which is mainly the reason I am bringing this up again) but then 
>again it may give them too much of a head start.
No, because then networkx becomes a dependency and a moving target. And 
it delivers way too much utilities, so people would start digging in 
networkx docs (and complaining with us when something does not work as 
they expect) instead of focusing on getting something that moves.

>So yeah, I am probably not too convinced myself either.
Exactly, so I suggest to close the issues as a WontFix :P
