### ISSUE TITLE
Show noisy ghost positions in UI

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#347]
Have the UI optionally show the position of where the currently moving bot has experienced the other bots when their position is noisy.

**Comment by Debilski** [comment]
@otizonaizit Is this something worth adding to grid view? It would need some polishing and a way to better show whose shadow bots we are seeing.

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/216179/63028756-b4992380-beaf-11e9-998f-fcd81992a369.png">

**Comment by otizonaizit** [comment]
Yes, it is good. Maybe a bit fantier color? But then, I think we should rename the `show grid` button to `details` or, maybe better `debug`.

**Comment by otizonaizit** [comment]
In case you plan to add it (you have the code already?), then we should mention and show this in pelita_template, see https://github.com/ASPP/pelita_template/issues/13

**Comment by Debilski** [comment]
> Maybe a bit fantier color?

fainter or fancier? :) I’ll try to make it both.

The version above is already coded but its still a hack in a few places. Will clean it up later.

**Comment by otizonaizit** [comment]
>>Maybe a bit fantier color?
>
>fainter or fancier? :) I’ll try to make it both.
>

I meant fantier, but it can be fancier too, of course ;)

>The version above is already coded but its still a hack in a few places. Will clean it up later.
>

Does "later" means in time for ASPP-2019? If that's the plan, please make a WIP-PR so that I can work/have a look at it. If it is for later, then it's fine. The reason I ask is that if this goes in, the docs in pelita_template, which I am working on right now, must mention it.

I think if we go so far, we could also show sight-radius and noise-radius for the current bot. That would make debugging indeed much easier. 

We would have to see how discernible it is when you also show sight-radius and noise-radius for the current bot. Maybe one could show all of this (noisy enemies + sight and noise radius) only when using "step". Otherwise I expect a lot of flickering. But we'd have to see it implemented first.

**Comment by Debilski** [comment]
> I think if we go so far, we could also show sight-radius and noise-radius for the current bot. That would make debugging indeed much easier.

Not sure if the noise radius is so helpful when using the Tk UI. You basically know already where the your bot sees the other bots, if the shadows are activated; it’s not really a useful information to you that the enemy could also have appeared to you five steps in the other direction, when you already know that it has appeared right in front of you, no?
The shadow bots are at least going to have an effect on most algorithms, so knowing where they are helps you understand what your code does. (I’d also prefer if they can be deactivated but I also don’t want to make the UI more complicated.)

What is more useful is to show the potentially _real_ positions, given a noised bot, but this is something the students can do themselves in the notebook with matplotlib. Adding this to the Tk UI would be really confusing, I’d say.

Draft branch is coming in a few minutes.
