### ISSUE TITLE
Last-minute fixes should also be merged via PR

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#370]
I’m okay with documentation typo fixes to go directly to master, if time constraints dictate.

Bug fixes (and especially fixes for the subtlest of bugs) should still be done through PR. Only then do we have tracking in GitHub and can reference to the PR for later additions.

**Comment by Debilski** [comment]
( @jakobj @keszybz @otizonaizit )

**Comment by otizonaizit** [comment]
Yep, but the real issue here is that there should be **no** last-minute fixes. So it is not a matter of behavior, it is a matter of existence...

**Comment by Debilski** [comment]
Well, I guess we know how to close a repo now so let’s enforce that a week in advance. There is no other solution.

**Comment by keszybz** [comment]
Also locking down the repo one week in advance won't work: you work
on pelita always during the school, and other people sometimes a bit
too, and we shouldn't disallow that.

It's always good to review any last minute changes, so if doing that
through a PR is easier than having some look over your should and
provide their review, then sure, we should do a PR. But as Tiziano
said, the problem is in having to have the fix, not in the way it is
done, so putting artificial constraints on the process is not be the
point.

**Comment by Debilski** [comment]
I know, I was being hyperbolic on purpose.

**Comment by Debilski** [comment]
Anyway: The fix was not needed for the tournament. I would have worked just fine 99.9% guaranteed. ;)

**Comment by jakobj** [comment]
sorry about that! i feel really bad about pushing to master - it won't happen again. :(
