### ISSUE TITLE
Simulate next state

### ISSUE THREAD

**Issue by DoriekeG** [ASPP/pelita#398]
During the programming of our bot we ran into the problem that there was no method that would simulate a move for a player. @Debilski said that due to the way it is programmed, it is hard to simulate the next state completely (including food eaten etc). A very simple method in pelita.player which takes a move and returns the current position plus that move would already be a good step in the right direction, and this is easy to implement on the short-term. It would however save a lot of fuss with manually checking all things that change in the next state (position, whether bot is harvester, if food is eaten, points) if the entire next state is available. What do you think?

**Comment by Debilski** [comment]
Simulating a move is roughly possible already, if you make a copy of the universe before setting the next move:

    # .. in some AbstractPlayer subclass
    def get_move():
        uni = self.current_uni.copy()
        uni.move_bot(self._index, test_move)
        # if test_move eats a food pellet or kills an enemy,
        # uni will have changed accordingly

The problem is of course, that all the helper methods in AbstractPlayer will not work anymore so that you will have to use the Universe methods directly.

But you’re right that we could should possibly add something like this as a helper to AbstractPlayer:

    def simulate_move(self, move):
        uni = self.current_uni.copy()
        new_state = uni.move_bot(self._index, test_move)
        return (new_state, universe)

Or, we just get around to finally implementing #52.

---

This may be a little far out but I wonder if we could also have the following syntax working:

    def get_move(self):
        move = ... # some_move
        with self.simulated_move(move) as moved_self:
            # moved_self is now self but at the new position
            if len(moved_self.enemy_food) < len(self.enemy_food):
                # seems like we ate something. let’s accept this move
                return move

Won’t probably work in the general case though unless we drop inheritance.

**Comment by Debilski** [comment]
Is #399 what you were thinking of, @DoriekeG ?

**Comment by DoriekeG** [comment]
Yes, that was exactly what I meant.
