### ISSUE TITLE
Automated doc builds

### ISSUE THREAD

**Issue by fmaussion** [ASPP/pelita#525]
How do you guys build (and deploy) the documentation currently?

I'm asking because (i) you folks did a lot of change recently and I don't see the new API being documented anywhere, which makes the current documentation really outdated and (ii) my recent [PR](https://github.com/ASPP/pelita/pull/484) is still not visible online.

Would you consider switching to automated doc builds like ReadTheDocs for Pelita? I'm happy to help in the set-up if you need it.

**Comment by Debilski** [comment]
Hi, the new API is currently documented here: https://github.com/ASPP/pelita_template
It is still in a test phase and we don’t want to completely abandon the old system (at least at the moment it is still working), so we have not touched the docs yet.

We do have an automatic updating system for the docs though. (Could be that it is currently broken because of travis deployment key issues.)

**Comment by Debilski** [comment]
Automated docs fixed in #539.
