### ISSUE TITLE
How to profile?

### ISSUE THREAD

**Issue by jni** [ASPP/pelita#545]
Running `kernprof /path/to/pelita --null my_player.py my_player.py` fails because the players are run in subprocesses. Some guidance on how to profile players would be useful!

**Comment by Debilski** [comment]
The tricky part is that most profilers expect a script on the command line. Our players however are run as a module `python -m pelita.scripts.pelita_player myplayer.py`. If you have a profiler that can run modules then we could just change the command line, otherwise things are a little more tricky.

**Comment by Debilski** [comment]
I think we have something in #555, @jni.
