### ISSUE TITLE
Check for imbalance issue between left and right sides

### ISSUE THREAD

**Issue by jni** [ASPP/pelita#551]
Some students are reporting that blue wins much more than red regardless of which bots you use. We will see in the tournament but I wonder if there is something to be done with that...

**Comment by otizonaizit** [comment]
Another explanation would be that if you are playing with two teams that use exactly the same code (which is typical while you test your own bots), then the blue has a little advantage, because it gets first on the border and it is the first that can kill the enemy. This advantage is not removable as long as you play turn-based. But blue and red are selected at random in the tournament, so it shouldn't influence the final result too much, no?

**Comment by Debilski** [comment]
I did 2x100 rounds with the Apac groups 0 and 1:

    group0 vs group1: [62 wins for blue, 38 losses, 0 draws]
    group1 vs group0: [33 wins for blue, 61 losses, 6 draws]

So far it doesn’t look suspicious but we can make a bigger statistics of course. (Historically, some teams wrote better routines for the blue bots because they hardcoded some stuff or did the calculations slightly wrong when playing on the far side, so this also needs to be taken into account.)

**Comment by otizonaizit** [comment]
In absence of further evidence, this can be closed.

**Comment by jni** [comment]
What? We have full power to gather this evidence! I suggest we run round robins x 100 like @Debilski did above, gathering not just wins but scores. This may give us a fair handicap to give to the red team. Note that 6 losses out of 38 converted to draws could be quite significant, if it's a consistent bias!

**Comment by otizonaizit** [comment]
@jni : not sure what we are talking about here. It's not like having statistics on group0 vs group 1 games tells us much about an (fully hypothetical) bug in pelita. The bug could well be in their code. As I said, there is a bias inherent to the way pelita works (by sequentially moving bots in a round), but apart from that, it needs to be demostrated in the **code** that there is a problem. The stats are not really conclusive. If anyone has time to spend on this, I am willing to re-open the issue, otherwise I would keep it closed as not-a-bug.

**Comment by jni** [comment]
Ok, firstly, I just realised that the above numbers actually support a small bias towards *RED*, not blue, so I retract my objection. I just got confused with the wins/losses vs blue wins/red wins.

However, I just want to note that in principle this is *not* an argument about specific bots, and everything else is random. The experiment is to test whether for *any* matchup, you get a bias towards the blue side, *on average*. We have a rich repertoire of bots that we can test in one direction and then the other, which we could use to test whether there is a consistent bias. (And to quantify that bias.)

It could well be that it doesn't exist, but my point is that this is a testable hypothesis and not at all dependent on individual bots, just like it is known that there is a small bias towards white in chess and this fact does not depend on individual players (even though some players might actually do better as black).

**Comment by Debilski** [comment]
Hmm, I don’t know. I mean, we do have a certain number of bots but it is not nearly as many as there are chess players. (Unless you want to adapt code it might be fewer than 15 working implementations.) So it is questionable if doing statistics is really helpful here. (And the bots are not nearly as good as the chess players who are usually analysed for this.)
I am quite sure that some _implementations_ perform better on one side than on the other (or might even have severe bugs when run on the wrong side) so that in the end we wouldn’t learn much about the bias in the game. We would just learn about which side is currently more optimal for most implementations.

I’m still unsure what to do about our indeed biased a_star:

    print(show_shortest_path(layout1))
    ##################
    # .............0 #
    # .              #
    # .              #
    # 1              #
    ##################

    print(show_shortest_path(layout2))
    ##################
    # .............1 #
    # .              #
    # .              #
    # 0              #
    ##################

In an admittedly subcomplex example, we have two layouts with the a_star path that moves 0 onto the position of 1. The paths are the same in both cases but they are not symmetric given rotation. In layout1 our bot 0 would spend much more time in the enemy’s territory being at a higher risk potentially.

Seriously: Maybe we could introduce a random tie breaker in the heap queue of the a_star that would also give us nicer paths such as:

    ##################
    #            ..1 #
    #         ....   #
    #       ...      #
    # 0......        #
    ##################

**Comment by jni** [comment]
Why not deprecate A* and pelita Graph in favour of using only networkx?

**Comment by Debilski** [comment]
Not if networkx has the same bias. ;) (Not checking this tonight though.)
