### ISSUE TITLE
Default player fails with a non existing path.

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#681]
SmartEatingPlayers fail when food cannot be reached.

    cat layout
    ########
    #. # .3#
    #. ##.1#
    #0.## .#
    #2.#  .#
    ########

    pelita --layout layout

        raise nx.NetworkXNoPath("No path between %s and %s." % (source, target))
    networkx.exception.NetworkXNoPath: No path between (1, 3) and (5, 1).

I know it is not needed in a normal situation, but when testing Tk, these mazes are useful sometimes, so it shouldn’t fail stupidly.

**Comment by otizonaizit** [comment]
This deserves a serious discussion that goes beyond this single example. Pelita code needs to become "educational" level. There are many places already that, in order to support impossible or illegal situation, are using complicated constructs (for example, the `max_rounds==0` things, or this one with `nx.NetworkXNoPath`, but there are many other cases.
This complicates the code for no gain. I don't understand the idea of writing code that is used to pass tests that are testing things that can not happen. I insist that we should catch impossible or invalid input early and fail immediately, without trying to support eveywhere the illegal things.
In this particular case, I don't see what it means that these mazes are usefule _sometimes_ to test TK. Why? Why can't we test TK only in situations that can indeed happen during a pelita game?
It is like the madness we had in the past of trying to support more than 2 bots per team. Why?
