### ISSUE TITLE
Show group numbers next to the group names during the tournament

### ISSUE THREAD

**Issue by nimpy** [ASPP/pelita#737]
As the group names are only revealed just before the tournament, it was hard to keep track of which group name corresponds to which group number, so having both information would have been useful.

**Comment by lschwetlick** [comment]
You mean during the tournament, to know which group you are currently cheering for? Or for your bots to  have access to the group name?

**Comment by nimpy** [comment]
I meant the former, i.e. during the tournament (in the GUI and in the terminal where the information about the upcoming matches, stats, etc. is printed) -- basically wherever the group names are shown, I would have liked to see the group number too. 

The reasoning for this: Throughout the course when I was talking to people, everyone was referring to their group by the group number (and secretive about the group name). However, during the tournament I could no longer associate the groups with their members because now the groups were referred to by their freshly-revealed names.

**Comment by Debilski** [comment]
If printing it just before a match (and possible thereafter, when announcing the winner) is enough, you can try to add it to this line https://github.com/ASPP/pelita/blob/1429024fca389691f260622fc539017703411d89/pelita/tournament/__init__.py#L482

We do not store the group number specifically in our yaml config (it looks like this: https://github.com/ASPP/pelita/blob/main/tournament.yaml but instead of `pelita/player/StoppingPlayer` it references the `group0.py` files), however, but we generate an `id` (which is just `"#0"`, …, `"#4"` per default) in the `Config` class: https://github.com/ASPP/pelita/blob/1429024fca389691f260622fc539017703411d89/pelita/tournament/__init__.py#L235-L253

This `id` is what is passed around in the tournament file (as `team1`, `team2` in the `config.print` example), so I guess, we can just also print the `team1` variable itself in addition to the team name.

**Comment by Debilski** [comment]
Somewhat related to the wider problem of finding one’s group easily during the tournament: We could colourise (or at least add some sort of colour sprinkle) the bots differently from the classic red–blue scheme during the tournament (see #574).

**Comment by otizonaizit** [comment]
I think adding the group number in the GUI, so that the group name reads "Cool Name - N" where N is the group number is sufficient, straightforward and easy to implement, if we adjust the yml input data to also store the group number.
