### ISSUE TITLE
Adopt SciPy SPEC 7 on Seeding Pseudo-Random Number Generation

### ISSUE THREAD

**Issue by otizonaizit** [ASPP/pelita#827]
This seems to be the new standard. I am not sure if we are already doing the right thing. We should check:

https://scientific-python.org/specs/spec-0007/

**Comment by otizonaizit** [comment]
It seems to boil down to initialize the random generator with:

```python
import numpy as np
SEED = 12345
np.random.default_rng(SEED)
```

we are doing

```python
import random
SEED = 12345
random.Random(SEED)
```

is is worth to depend on numpy for this?

**Comment by Debilski** [comment]
We depend on numpy already (if only in the maze generator).

But as far as I understand it, the main idea is that they want to discourage re-seeding (which makes sense) in favour of generating a new RNG object with a given seed (which is then supposed to be passed as a context object to functions instead of relying on the global RNG). To get the same effect, I think we could simply change all occurrences of

    random.seed(SEED)

with

   rng = random.Random(SEED)

(+ streamline the code that we never rely on the global RNG either)

**Comment by Debilski** [comment]
We kind of do it already like this in the noiser in `gamestate_filters` btw.
